<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!DOCTYPE tomtom[
<!ELEMENT tomtom (model, targets, queries, runtime)>
<!ATTLIST tomtom version CDATA #REQUIRED release CDATA #REQUIRED>
<!ELEMENT model (command_line, distance_measure, threshold, background, host, when)>
<!ELEMENT command_line (#PCDATA)>
<!ELEMENT distance_measure EMPTY>
<!ATTLIST distance_measure value (allr|blic1|blic5|ed|kullback|llr1|llr5|pearson|sandelin) #REQUIRED>
<!ELEMENT threshold (#PCDATA)>
<!ATTLIST threshold type (evalue|qvalue) #REQUIRED>
<!ELEMENT background EMPTY>
<!ATTLIST background from (first_target|file) #REQUIRED A CDATA #REQUIRED C CDATA #REQUIRED G CDATA #REQUIRED T CDATA #REQUIRED file CDATA #IMPLIED>
<!ELEMENT host (#PCDATA)>
<!ELEMENT when (#PCDATA)>
<!-- each target is listed in order that the target was specified to the command line
     the motifs are not listed in any particular order -->
<!ELEMENT targets (target_file*)>
<!ELEMENT target_file (motif*)>
<!ATTLIST target_file index CDATA #REQUIRED source CDATA #REQUIRED name CDATA #REQUIRED 
  loaded CDATA #REQUIRED excluded CDATA #REQUIRED last_mod_date CDATA #REQUIRED>
<!-- currently there can only be one query file (but users should not assume this will always be true)
     the query motifs are specified in the order that they appear in the file
     the matches are ordered from best to worst -->
<!ELEMENT queries (query_file*)>
<!ELEMENT query_file (query*)>
<!ATTLIST query_file source CDATA #REQUIRED name CDATA #REQUIRED last_mod_date CDATA #REQUIRED>
<!ELEMENT query (motif,match*)>
<!ELEMENT match EMPTY>
<!ATTLIST match target IDREF #REQUIRED orientation (forward|reverse) "forward" 
  offset CDATA #REQUIRED pvalue CDATA #REQUIRED evalue CDATA #REQUIRED qvalue CDATA #REQUIRED>
<!-- motif contains the probability of each of the nucleotide bases at each position;
     i starts at 1; A, C, G and T are probabilities that sum to 1 -->
<!ELEMENT motif (pos*)>
<!ATTLIST motif id ID #REQUIRED name CDATA #REQUIRED alt CDATA #IMPLIED length CDATA #REQUIRED 
  nsites CDATA #IMPLIED evalue CDATA #IMPLIED url CDATA #IMPLIED>
<!ELEMENT pos EMPTY>
<!ATTLIST pos i CDATA #REQUIRED A CDATA #REQUIRED C CDATA #REQUIRED G CDATA #REQUIRED T CDATA #REQUIRED>
<!ELEMENT runtime EMPTY>
<!ATTLIST runtime cycles CDATA #REQUIRED seconds CDATA #REQUIRED>
]>
<tomtom version="4.9.0" release="Wed Oct  3 11:07:26 EST 2012">
	<model>
		<command_line>tomtom -no-ssc -oc DeepSEA_TOMTOM -verbosity 4 -min-overlap 5 -dist pearson -evalue -thresh 0.01 DeepSEA.meme /data/users/dxquang/meme_4.11.0/motif_databases/EUKARYOTE/jolma2013.meme /data/users/dxquang/meme_4.11.0/motif_databases/JASPAR/JASPAR_CORE_2016_vertebrates.meme /data/users/dxquang/meme_4.11.0/motif_databases/MOUSE/uniprobe_mouse.meme</command_line>
		<distance_measure value="pearson"/>
		<threshold type="evalue">0.01</threshold>
		<background from="first_target" A="0.25" C="0.25" G="0.25" T="0.25"/>
		<host>compute-2-10.local</host>
		<when>Fri Jan 22 11:22:45 2016</when>
	</model>
	<targets>
		<target_file index="1" source="/data/users/dxquang/meme_4.11.0/motif_databases/EUKARYOTE/jolma2013.meme" name="jolma2013.meme" loaded="843" excluded="0" last_mod_date="Mon Dec  7 16:08:34 2015">
			<motif id="t_1_CTCF_full" name="CTCF_full" length="17" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=CTCF_full">
				<pos i="1" A="0.455332" C="0.045844" G="0.145508" T="0.353317"/>
				<pos i="2" A="0.173692" C="0.024785" G="0.759303" T="0.042221"/>
				<pos i="3" A="0" C="0.940984" G="0" T="0.059016"/>
				<pos i="4" A="0.005067" C="0" G="0.988124" T="0.006809"/>
				<pos i="5" A="0.062318" C="0.932432" G="0.000778" T="0.004472"/>
				<pos i="6" A="0.004531" C="0.995469" G="0" T="0"/>
				<pos i="7" A="0.507584" C="0.453365" G="0.018044" T="0.021008"/>
				<pos i="8" A="0.007862" C="0.640792" G="0" T="0.351346"/>
				<pos i="9" A="0" C="0.999887" G="0.000113" T="0"/>
				<pos i="10" A="0.002595" C="0.003436" G="0.001613" T="0.992356"/>
				<pos i="11" A="0.76366" C="0.02096" G="0.117447" T="0.097933"/>
				<pos i="12" A="0.007318" C="0.131403" G="0.799154" T="0.062124"/>
				<pos i="13" A="0.013768" C="0.387978" G="0" T="0.598255"/>
				<pos i="14" A="0.000233" C="0" G="0.985689" T="0.014078"/>
				<pos i="15" A="0.039788" C="0.011172" G="0.73138" T="0.21766"/>
				<pos i="16" A="0.151957" C="0.281977" G="0.008169" T="0.557898"/>
				<pos i="17" A="0.364415" C="0.310527" G="0.212438" T="0.11262"/>
			</motif>
			<motif id="t_1_ELF5_DBD" name="ELF5_DBD" length="11" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=ELF5_DBD">
				<pos i="1" A="0.692198" C="0.038653" G="0.063078" T="0.206071"/>
				<pos i="2" A="0.20931" C="0.457356" G="0.177176" T="0.156158"/>
				<pos i="3" A="0.202296" C="0.499059" G="0.283779" T="0.014866"/>
				<pos i="4" A="0.33994" C="0.612021" G="0.040069" T="0.007971"/>
				<pos i="5" A="0" C="0" G="0.993912" T="0.006088"/>
				<pos i="6" A="0" C="0" G="0.994748" T="0.005252"/>
				<pos i="7" A="1" C="0" G="0" T="0"/>
				<pos i="8" A="0.933389" C="0.000833" G="0" T="0.065779"/>
				<pos i="9" A="0.167404" C="0.027008" G="0.800233" T="0.005355"/>
				<pos i="10" A="0.079504" C="0.149127" G="0.055377" T="0.715993"/>
				<pos i="11" A="0.348157" C="0.135242" G="0.296071" T="0.22053"/>
			</motif>
			<motif id="t_1_ELF5_full" name="ELF5_full" length="11" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=ELF5_full">
				<pos i="1" A="0.642212" C="0.066986" G="0.080011" T="0.210792"/>
				<pos i="2" A="0.228652" C="0.430337" G="0.178839" T="0.162172"/>
				<pos i="3" A="0.205497" C="0.510722" G="0.263585" T="0.020196"/>
				<pos i="4" A="0.335095" C="0.581016" G="0.071018" T="0.012871"/>
				<pos i="5" A="0.000901" C="0" G="0.993093" T="0.006006"/>
				<pos i="6" A="0.001495" C="0" G="0.991031" T="0.007474"/>
				<pos i="7" A="0.994107" C="0.004052" G="0.000368" T="0.001473"/>
				<pos i="8" A="0.896341" C="0.020664" G="0" T="0.082995"/>
				<pos i="9" A="0.223281" C="0.038886" G="0.716759" T="0.021074"/>
				<pos i="10" A="0.12" C="0.180126" G="0.078491" T="0.621384"/>
				<pos i="11" A="0.348094" C="0.134664" G="0.276588" T="0.240653"/>
			</motif>
			<motif id="t_1_ELK4_DBD" name="ELK4_DBD" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=ELK4_DBD">
				<pos i="1" A="0.671011" C="0.055787" G="0.165557" T="0.107645"/>
				<pos i="2" A="0.074097" C="0.846037" G="0.065647" T="0.014219"/>
				<pos i="3" A="0.060524" C="0.936766" G="0.00271" T="0"/>
				<pos i="4" A="0" C="0.000998" G="0.999002" T="0"/>
				<pos i="5" A="0" C="0" G="0.986009" T="0.013991"/>
				<pos i="6" A="0.996842" C="0.002438" G="0" T="0.000721"/>
				<pos i="7" A="0.819717" C="0.014087" G="0.000847" T="0.165349"/>
				<pos i="8" A="0.326864" C="0.029842" G="0.638077" T="0.005217"/>
				<pos i="9" A="0.035594" C="0.303084" G="0.044663" T="0.616659"/>
				<pos i="10" A="0.271465" C="0.20093" G="0.362769" T="0.164836"/>
			</motif>
			<motif id="t_1_ERF_DBD" name="ERF_DBD" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=ERF_DBD">
				<pos i="1" A="0.836735" C="0.016327" G="0.134694" T="0.012245"/>
				<pos i="2" A="0.027559" C="0.807087" G="0.031496" T="0.133858"/>
				<pos i="3" A="0.105932" C="0.868644" G="0.025424" T="0"/>
				<pos i="4" A="0" C="0" G="1" T="0"/>
				<pos i="5" A="0" C="0.014423" G="0.985577" T="0"/>
				<pos i="6" A="0.962441" C="0.014085" G="0.014085" T="0.00939"/>
				<pos i="7" A="0.87234" C="0" G="0" T="0.12766"/>
				<pos i="8" A="0.269737" C="0.055921" G="0.674342" T="0"/>
				<pos i="9" A="0" C="0.159533" G="0.042802" T="0.797665"/>
				<pos i="10" A="0.303922" C="0.137255" G="0.45098" T="0.107843"/>
			</motif>
			<motif id="t_1_ERG_DBD_1" name="ERG_DBD_1" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=ERG_DBD_1">
				<pos i="1" A="0.690772" C="0.040545" G="0.12829" T="0.140393"/>
				<pos i="2" A="0.113194" C="0.80007" G="0.069739" T="0.016997"/>
				<pos i="3" A="0.121438" C="0.873207" G="0.004207" T="0.001147"/>
				<pos i="4" A="0.000219" C="0" G="0.999781" T="0"/>
				<pos i="5" A="0" C="0.000218" G="0.993473" T="0.00631"/>
				<pos i="6" A="0.994121" C="0.004354" G="0" T="0.001524"/>
				<pos i="7" A="0.769075" C="0.020044" G="0.001179" T="0.209702"/>
				<pos i="8" A="0.423945" C="0.021304" G="0.548786" T="0.005965"/>
				<pos i="9" A="0.02062" C="0.238712" G="0.053432" T="0.687237"/>
				<pos i="10" A="0.220324" C="0.240911" G="0.365309" T="0.173456"/>
			</motif>
			<motif id="t_1_ERG_full_1" name="ERG_full_1" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=ERG_full_1">
				<pos i="1" A="0.721634" C="0.039976" G="0.127866" T="0.110523"/>
				<pos i="2" A="0.084584" C="0.837312" G="0.070941" T="0.007162"/>
				<pos i="3" A="0.092421" C="0.907579" G="0" T="0"/>
				<pos i="4" A="0" C="0" G="0.997967" T="0.002033"/>
				<pos i="5" A="0" C="0" G="0.994733" T="0.005267"/>
				<pos i="6" A="0.99232" C="0.001213" G="0.001617" T="0.00485"/>
				<pos i="7" A="0.83817" C="0.006145" G="0" T="0.155685"/>
				<pos i="8" A="0.371497" C="0.014011" G="0.611289" T="0.003203"/>
				<pos i="9" A="0.020121" C="0.259372" G="0.043826" T="0.676681"/>
				<pos i="10" A="0.241141" C="0.197963" G="0.402037" T="0.158859"/>
			</motif>
			<motif id="t_1_ETS1_DBD_1" name="ETS1_DBD_1" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=ETS1_DBD_1">
				<pos i="1" A="0.710917" C="0.055644" G="0.169581" T="0.063858"/>
				<pos i="2" A="0.056568" C="0.84318" G="0.093338" T="0.006914"/>
				<pos i="3" A="0.136437" C="0.861316" G="0.002247" T="0"/>
				<pos i="4" A="0" C="0.007766" G="0.992234" T="0"/>
				<pos i="5" A="0" C="0" G="0.995547" T="0.004453"/>
				<pos i="6" A="1" C="0" G="0" T="0"/>
				<pos i="7" A="0.738711" C="0.002478" G="0.008535" T="0.250275"/>
				<pos i="8" A="0.405893" C="0.007735" G="0.581952" T="0.00442"/>
				<pos i="9" A="0.030743" C="0.245941" G="0.042832" T="0.680484"/>
				<pos i="10" A="0.299292" C="0.14946" G="0.403653" T="0.147596"/>
			</motif>
			<motif id="t_1_ETS1_full_1" name="ETS1_full_1" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=ETS1_full_1">
				<pos i="1" A="0.655163" C="0.091208" G="0.14407" T="0.109559"/>
				<pos i="2" A="0.078411" C="0.841069" G="0.073136" T="0.007384"/>
				<pos i="3" A="0.11551" C="0.86887" G="0.015619" T="0"/>
				<pos i="4" A="0" C="0" G="1" T="0"/>
				<pos i="5" A="0" C="0.002914" G="0.995837" T="0.001249"/>
				<pos i="6" A="0.994595" C="0.002079" G="0.003326" T="0"/>
				<pos i="7" A="0.680512" C="0.038122" G="0.001991" T="0.279374"/>
				<pos i="8" A="0.462158" C="0.033816" G="0.500805" T="0.003221"/>
				<pos i="9" A="0.044513" C="0.36109" G="0.037606" T="0.556792"/>
				<pos i="10" A="0.289837" C="0.211209" G="0.341698" T="0.157256"/>
			</motif>
			<motif id="t_1_ETV6_full_2" name="ETV6_full_2" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=ETV6_full_2">
				<pos i="1" A="0.415409" C="0.28956" G="0.20669" T="0.088342"/>
				<pos i="2" A="0.045789" C="0.320525" G="0.574642" T="0.059044"/>
				<pos i="3" A="0.17243" C="0.74521" G="0.046379" T="0.035981"/>
				<pos i="4" A="0.001044" C="0" G="0.997018" T="0.001938"/>
				<pos i="5" A="0.00312" C="0" G="0.993611" T="0.003269"/>
				<pos i="6" A="0.998954" C="0" G="0.001046" T="0"/>
				<pos i="7" A="0.987303" C="0.001919" G="0.004725" T="0.006053"/>
				<pos i="8" A="0.102305" C="0.006927" G="0.890769" T="0"/>
				<pos i="9" A="0.02318" C="0.105064" G="0.029352" T="0.842404"/>
				<pos i="10" A="0.306415" C="0.051144" G="0.479288" T="0.163152"/>
			</motif>
			<motif id="t_1_Elf5_DBD" name="Elf5_DBD" length="11" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=Elf5_DBD">
				<pos i="1" A="0.608955" C="0.067463" G="0.096119" T="0.227463"/>
				<pos i="2" A="0.211125" C="0.404551" G="0.189633" T="0.19469"/>
				<pos i="3" A="0.207538" C="0.508609" G="0.261517" T="0.022336"/>
				<pos i="4" A="0.328738" C="0.575822" G="0.081654" T="0.013786"/>
				<pos i="5" A="0" C="0" G="1" T="0"/>
				<pos i="6" A="0" C="0.000743" G="0.998514" T="0.000743"/>
				<pos i="7" A="0.984153" C="0.005838" G="0" T="0.010008"/>
				<pos i="8" A="0.876046" C="0.020532" G="0.006084" T="0.097338"/>
				<pos i="9" A="0.254835" C="0.069966" G="0.662116" T="0.013083"/>
				<pos i="10" A="0.1279" C="0.195246" G="0.091115" T="0.585739"/>
				<pos i="11" A="0.342128" C="0.15234" G="0.271489" T="0.234043"/>
			</motif>
			<motif id="t_1_FEV_DBD" name="FEV_DBD" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=FEV_DBD">
				<pos i="1" A="0.658581" C="0.052149" G="0.141274" T="0.147997"/>
				<pos i="2" A="0.124267" C="0.773227" G="0.076587" T="0.02592"/>
				<pos i="3" A="0.077555" C="0.915625" G="0.006442" T="0.000379"/>
				<pos i="4" A="0.00179" C="0" G="0.997935" T="0.000275"/>
				<pos i="5" A="0.000275" C="0.000138" G="0.998347" T="0.001239"/>
				<pos i="6" A="0.995605" C="0.001511" G="0.000412" T="0.002472"/>
				<pos i="7" A="0.754711" C="0.016033" G="0.000625" T="0.228631"/>
				<pos i="8" A="0.300952" C="0.033197" G="0.657506" T="0.008345"/>
				<pos i="9" A="0.043796" C="0.179621" G="0.061551" T="0.715033"/>
				<pos i="10" A="0.294426" C="0.187362" G="0.311396" T="0.206816"/>
			</motif>
			<motif id="t_1_FLI1_DBD_1" name="FLI1_DBD_1" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=FLI1_DBD_1">
				<pos i="1" A="0.651254" C="0.06368" G="0.181043" T="0.104022"/>
				<pos i="2" A="0.086933" C="0.810036" G="0.086487" T="0.016544"/>
				<pos i="3" A="0.102314" C="0.892339" G="0.005238" T="0.000109"/>
				<pos i="4" A="0" C="0" G="1" T="0"/>
				<pos i="5" A="0" C="0.001037" G="0.997743" T="0.00122"/>
				<pos i="6" A="0.998535" C="0.000855" G="6.1e-05" T="0.00055"/>
				<pos i="7" A="0.734999" C="0.0289" G="0.001079" T="0.235022"/>
				<pos i="8" A="0.45581" C="0.027045" G="0.507719" T="0.009427"/>
				<pos i="9" A="0.031918" C="0.286268" G="0.061897" T="0.619916"/>
				<pos i="10" A="0.211582" C="0.282395" G="0.359261" T="0.146762"/>
			</motif>
			<motif id="t_1_FLI1_full_1" name="FLI1_full_1" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=FLI1_full_1">
				<pos i="1" A="0.797388" C="0.02671" G="0.093888" T="0.082015"/>
				<pos i="2" A="0.060129" C="0.895689" G="0.038182" T="0.006001"/>
				<pos i="3" A="0.060367" C="0.937696" G="0.001936" T="0"/>
				<pos i="4" A="0.000115" C="0" G="0.999839" T="4.6e-05"/>
				<pos i="5" A="0" C="0" G="0.998625" T="0.001375"/>
				<pos i="6" A="0.998831" C="0.000481" G="0.000435" T="0.000252"/>
				<pos i="7" A="0.873379" C="0.004609" G="0.000481" T="0.121531"/>
				<pos i="8" A="0.431859" C="0.012728" G="0.553536" T="0.001876"/>
				<pos i="9" A="0.019303" C="0.24044" G="0.042738" T="0.697519"/>
				<pos i="10" A="0.244161" C="0.177029" G="0.425825" T="0.152985"/>
			</motif>
			<motif id="t_1_GBX2_DBD_2" name="GBX2_DBD_2" length="14" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=GBX2_DBD_2">
				<pos i="1" A="0.034663" C="0.089971" G="0.0057" T="0.869666"/>
				<pos i="2" A="0.657601" C="0.017808" G="0.037882" T="0.286709"/>
				<pos i="3" A="0.901696" C="0.019574" G="0.056764" T="0.021966"/>
				<pos i="4" A="0.05467" C="0.058359" G="0.113556" T="0.773416"/>
				<pos i="5" A="0.076462" C="0.03663" G="0.089833" T="0.797075"/>
				<pos i="6" A="0.190153" C="0.018079" G="0.774334" T="0.017433"/>
				<pos i="7" A="0.241183" C="0.225104" G="0.473202" T="0.060512"/>
				<pos i="8" A="0.063148" C="0.476522" G="0.259715" T="0.200615"/>
				<pos i="9" A="0.029954" C="0.710948" G="0.040138" T="0.218961"/>
				<pos i="10" A="0.765009" C="0.083978" G="0.074033" T="0.07698"/>
				<pos i="11" A="0.7579" C="0.106767" G="0.081057" T="0.054276"/>
				<pos i="12" A="0.022194" C="0.055486" G="0.018912" T="0.903407"/>
				<pos i="13" A="0.177537" C="0.019695" G="0.020123" T="0.782646"/>
				<pos i="14" A="0.886261" C="0.004731" G="0.063143" T="0.045866"/>
			</motif>
			<motif id="t_1_GLIS3_DBD" name="GLIS3_DBD" length="14" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=GLIS3_DBD">
				<pos i="1" A="0.008155" C="0.041794" G="0.687054" T="0.262997"/>
				<pos i="2" A="0.965675" C="0.004577" G="0.029748" T="0"/>
				<pos i="3" A="0" C="0.993127" G="0.003436" T="0.003436"/>
				<pos i="4" A="0" C="1" G="0" T="0"/>
				<pos i="5" A="0.00625" C="0.965625" G="0" T="0.028125"/>
				<pos i="6" A="0" C="0.99654" G="0" T="0.00346"/>
				<pos i="7" A="0.019608" C="0.980392" G="0" T="0"/>
				<pos i="8" A="0" C="0.91342" G="0" T="0.08658"/>
				<pos i="9" A="0.920042" C="0.001038" G="0.069574" T="0.009346"/>
				<pos i="10" A="0.004348" C="0.886957" G="0.034783" T="0.073913"/>
				<pos i="11" A="0.23323" C="0.017544" G="0.668731" T="0.080495"/>
				<pos i="12" A="0.8151" C="0.003082" G="0.047766" T="0.134052"/>
				<pos i="13" A="0.692063" C="0.177778" G="0.012698" T="0.11746"/>
				<pos i="14" A="0" C="0.025478" G="0.968153" T="0.006369"/>
			</motif>
			<motif id="t_1_JDP2_DBD_1" name="JDP2_DBD_1" length="9" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=JDP2_DBD_1">
				<pos i="1" A="0.899884" C="0.009626" G="0.088179" T="0.00231"/>
				<pos i="2" A="0.003396" C="0.004669" G="0" T="0.991935"/>
				<pos i="3" A="0" C="0.013767" G="0.974969" T="0.011264"/>
				<pos i="4" A="0.989416" C="0.007621" G="0" T="0.002964"/>
				<pos i="5" A="0.002979" C="0.54383" G="0.450638" T="0.002553"/>
				<pos i="6" A="0.002128" C="0.003404" G="0" T="0.994468"/>
				<pos i="7" A="0.010726" C="0.964109" G="0.025165" T="0"/>
				<pos i="8" A="0.995315" C="0.002555" G="0" T="0.002129"/>
				<pos i="9" A="0.005686" C="0.150675" G="0.013149" T="0.83049"/>
			</motif>
			<motif id="t_1_JDP2_full_1" name="JDP2_full_1" length="9" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=JDP2_full_1">
				<pos i="1" A="0.907274" C="0.01055" G="0.077735" T="0.004442"/>
				<pos i="2" A="0.003038" C="0.003645" G="0.000608" T="0.99271"/>
				<pos i="3" A="0" C="0.001808" G="0.984931" T="0.013261"/>
				<pos i="4" A="0.983153" C="0.000602" G="0.001203" T="0.015042"/>
				<pos i="5" A="0.008429" C="0.722456" G="0.261288" T="0.007827"/>
				<pos i="6" A="0.003645" C="0" G="0.003645" T="0.99271"/>
				<pos i="7" A="0.013189" C="0.979616" G="0.001799" T="0.005396"/>
				<pos i="8" A="0.995734" C="0" G="0" T="0.004266"/>
				<pos i="9" A="0.010654" C="0.195642" G="0.002421" T="0.791283"/>
			</motif>
			<motif id="t_1_Jdp2_DBD_1" name="Jdp2_DBD_1" length="9" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=Jdp2_DBD_1">
				<pos i="1" A="0.951841" C="0.005666" G="0.042493" T="0"/>
				<pos i="2" A="0" C="0" G="0" T="1"/>
				<pos i="3" A="0.00295" C="0" G="0.99115" T="0.0059"/>
				<pos i="4" A="1" C="0" G="0" T="0"/>
				<pos i="5" A="0" C="0.691395" G="0.305638" T="0.002967"/>
				<pos i="6" A="0" C="0" G="0" T="1"/>
				<pos i="7" A="0.002967" C="0.997033" G="0" T="0"/>
				<pos i="8" A="1" C="0" G="0" T="0"/>
				<pos i="9" A="0.005305" C="0.090186" G="0.013263" T="0.891247"/>
			</motif>
			<motif id="t_1_MESP1_DBD" name="MESP1_DBD" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=MESP1_DBD">
				<pos i="1" A="0.402098" C="0.255245" G="0.048951" T="0.293706"/>
				<pos i="2" A="0.470383" C="0.191638" G="0.317073" T="0.020906"/>
				<pos i="3" A="0" C="1" G="0" T="0"/>
				<pos i="4" A="0.885802" C="0.114198" G="0" T="0"/>
				<pos i="5" A="0" C="0.864458" G="0.093373" T="0.042169"/>
				<pos i="6" A="0.024096" C="0.864458" G="0.045181" T="0.066265"/>
				<pos i="7" A="0" C="0.111455" G="0" T="0.888545"/>
				<pos i="8" A="0" C="0.092814" G="0.859281" T="0.047904"/>
				<pos i="9" A="0.003484" C="0.365854" G="0.254355" T="0.376307"/>
				<pos i="10" A="0.222997" C="0.184669" G="0.324042" T="0.268293"/>
			</motif>
			<motif id="t_1_MNT_DBD" name="MNT_DBD" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=MNT_DBD">
				<pos i="1" A="0.409692" C="0.187959" G="0.212922" T="0.189427"/>
				<pos i="2" A="0.274596" C="0.334802" G="0.298091" T="0.092511"/>
				<pos i="3" A="0.037868" C="0.955119" G="0" T="0.007013"/>
				<pos i="4" A="0.970085" C="0" G="0" T="0.029915"/>
				<pos i="5" A="0" C="0.96733" G="0.009943" T="0.022727"/>
				<pos i="6" A="0.021552" C="0" G="0.978448" T="0"/>
				<pos i="7" A="0" C="0" G="0.021552" T="0.978448"/>
				<pos i="8" A="0" C="0" G="0.964589" T="0.035411"/>
				<pos i="9" A="0.219941" C="0.412023" G="0.192082" T="0.175953"/>
				<pos i="10" A="0.233138" C="0.335777" G="0.109971" T="0.321114"/>
			</motif>
			<motif id="t_1_SNAI2_DBD" name="SNAI2_DBD" length="9" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=SNAI2_DBD">
				<pos i="1" A="0.343086" C="0.142231" G="0.318372" T="0.196311"/>
				<pos i="2" A="0.431476" C="0.036015" G="0.40685" T="0.125659"/>
				<pos i="3" A="0.042022" C="0.90331" G="0.021851" T="0.032818"/>
				<pos i="4" A="0.947404" C="0.016328" G="0.006709" T="0.029559"/>
				<pos i="5" A="0.122184" C="0.011031" G="0.837552" T="0.029233"/>
				<pos i="6" A="0.003241" C="0" G="0.993859" T="0.0029"/>
				<pos i="7" A="0.000512" C="0.004717" G="0" T="0.99477"/>
				<pos i="8" A="0.104152" C="0.036544" G="0.720503" T="0.138802"/>
				<pos i="9" A="0.089047" C="0.339313" G="0.228849" T="0.342791"/>
			</motif>
			<motif id="t_1_SP1_DBD" name="SP1_DBD" length="11" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=SP1_DBD">
				<pos i="1" A="0.463014" C="0.022363" G="0.43205" T="0.082572"/>
				<pos i="2" A="0.192941" C="0.707016" G="0.033781" T="0.066262"/>
				<pos i="3" A="0.066297" C="0.754216" G="0.018711" T="0.160776"/>
				<pos i="4" A="0.470964" C="0.477062" G="0.049652" T="0.002323"/>
				<pos i="5" A="0.006066" C="0.990294" G="0.00182" T="0.00182"/>
				<pos i="6" A="0.300733" C="0.008674" G="0.488261" T="0.202333"/>
				<pos i="7" A="0" C="0.996642" G="0.000305" T="0.003053"/>
				<pos i="8" A="0.00183" C="0.996034" G="0.00061" T="0.001525"/>
				<pos i="9" A="0.001271" C="0.829733" G="0" T="0.168996"/>
				<pos i="10" A="0.389714" C="0.475875" G="0.015642" T="0.11877"/>
				<pos i="11" A="0.176778" C="0.517187" G="0.104546" T="0.201489"/>
			</motif>
			<motif id="t_1_SPIB_DBD" name="SPIB_DBD" length="14" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=SPIB_DBD">
				<pos i="1" A="0.473202" C="0.149801" G="0.242065" T="0.134931"/>
				<pos i="2" A="0.730775" C="0.030171" G="0.17475" T="0.064305"/>
				<pos i="3" A="0.934263" C="0.00772" G="0.021443" T="0.036574"/>
				<pos i="4" A="0.935538" C="0.003725" G="0.005346" T="0.055391"/>
				<pos i="5" A="0.750425" C="0.010264" G="0.018562" T="0.22075"/>
				<pos i="6" A="0.041493" C="0.090838" G="0.859351" T="0.008318"/>
				<pos i="7" A="0.345526" C="0.530445" G="0.121375" T="0.002654"/>
				<pos i="8" A="0.016787" C="0.000343" G="0.982617" T="0.000253"/>
				<pos i="9" A="0" C="0.000272" G="0.999093" T="0.000635"/>
				<pos i="10" A="0.995318" C="0.000809" G="0.001879" T="0.001994"/>
				<pos i="11" A="0.993118" C="0.001057" G="0.001856" T="0.00397"/>
				<pos i="12" A="0.012135" C="0.097383" G="0.887711" T="0.002771"/>
				<pos i="13" A="0.016948" C="0.043507" G="0.013468" T="0.926078"/>
				<pos i="14" A="0.407989" C="0.088984" G="0.256861" T="0.246167"/>
			</motif>
			<motif id="t_1_TCF4_full" name="TCF4_full" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=TCF4_full">
				<pos i="1" A="0.285714" C="0.33124" G="0.127159" T="0.255887"/>
				<pos i="2" A="0.407233" C="0.191824" G="0.314465" T="0.086478"/>
				<pos i="3" A="0.034139" C="0.907539" G="0.058321" T="0"/>
				<pos i="4" A="0.762246" C="0.044205" G="0.008363" T="0.185185"/>
				<pos i="5" A="0" C="0.862162" G="0.066216" T="0.071622"/>
				<pos i="6" A="0.096341" C="0.778049" G="0.047561" T="0.078049"/>
				<pos i="7" A="0" C="0.082014" G="0" T="0.917986"/>
				<pos i="8" A="0.083059" C="0.242599" G="0.524671" T="0.149671"/>
				<pos i="9" A="0.103448" C="0.333856" G="0.247649" T="0.315047"/>
				<pos i="10" A="0.308777" C="0.19279" G="0.225705" T="0.272727"/>
			</motif>
			<motif id="t_1_ZNF740_DBD" name="ZNF740_DBD" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=ZNF740_DBD">
				<pos i="1" A="0.273826" C="0.462576" G="0.177592" T="0.086007"/>
				<pos i="2" A="0.077809" C="0.85391" G="0.010719" T="0.057563"/>
				<pos i="3" A="0.062048" C="0.914152" G="0.002975" T="0.020824"/>
				<pos i="4" A="0.009485" C="0.971545" G="0.003613" T="0.015357"/>
				<pos i="5" A="0.009025" C="0.970668" G="0.005415" T="0.014892"/>
				<pos i="6" A="0.00362" C="0.973303" G="0.009502" T="0.013575"/>
				<pos i="7" A="0.0234" C="0.949669" G="0.016777" T="0.010155"/>
				<pos i="8" A="0.045264" C="0.901509" G="0.00964" T="0.043588"/>
				<pos i="9" A="0.680266" C="0.185642" G="0.036053" T="0.098039"/>
				<pos i="10" A="0.124568" C="0.618815" G="0.052934" T="0.203682"/>
			</motif>
			<motif id="t_1_ZNF740_full" name="ZNF740_full" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=ZNF740_full">
				<pos i="1" A="0.198051" C="0.570798" G="0.160537" T="0.070614"/>
				<pos i="2" A="0.022944" C="0.95976" G="0.00353" T="0.013766"/>
				<pos i="3" A="0.011319" C="0.961797" G="0.010435" T="0.016449"/>
				<pos i="4" A="0.013825" C="0.963843" G="0.010812" T="0.011521"/>
				<pos i="5" A="0.050442" C="0.890599" G="0.02866" T="0.030298"/>
				<pos i="6" A="0.006129" C="0.98035" G="0.007572" T="0.005949"/>
				<pos i="7" A="0.008991" C="0.977882" G="0.001439" T="0.011689"/>
				<pos i="8" A="0.016181" C="0.916568" G="0.011967" T="0.055284"/>
				<pos i="9" A="0.72652" C="0.070274" G="0.070808" T="0.132398"/>
				<pos i="10" A="0.075187" C="0.678055" G="0.033541" T="0.213217"/>
			</motif>
			<motif id="t_1_Zfp740_DBD" name="Zfp740_DBD" length="10" nsites="20" evalue="0.0e+000" url="http://floresta.eead.csic.es/footprintdb/index.php?db=HumanTF:1.0&amp;motif=Zfp740_DBD">
				<pos i="1" A="0.303121" C="0.341858" G="0.221888" T="0.133133"/>
				<pos i="2" A="0.185904" C="0.707181" G="0.027926" T="0.078989"/>
				<pos i="3" A="0.169679" C="0.775219" G="0.006706" T="0.048397"/>
				<pos i="4" A="0.04701" C="0.919115" G="0.008296" T="0.025579"/>
				<pos i="5" A="0.038354" C="0.927127" G="0.002789" T="0.031729"/>
				<pos i="6" A="0.062624" C="0.876401" G="0.013514" T="0.047462"/>
				<pos i="7" A="0.074532" C="0.843324" G="0.038059" T="0.044085"/>
				<pos i="8" A="0.113504" C="0.773865" G="0.031141" T="0.08149"/>
				<pos i="9" A="0.670956" C="0.104971" G="0.069897" T="0.154176"/>
				<pos i="10" A="0.162721" C="0.533507" G="0.070626" T="0.233146"/>
			</motif>
		</target_file>
		<target_file index="2" source="/data/users/dxquang/meme_4.11.0/motif_databases/JASPAR/JASPAR_CORE_2016_vertebrates.meme" name="JASPAR_CORE_2016_vertebrates.meme" loaded="519" excluded="0" last_mod_date="Mon Dec  7 16:08:44 2015">
			<motif id="t_2_MA0065.2" name="MA0065.2" alt="Pparg::Rxra" length="15" nsites="862" evalue="0.0e+000" url="http://jaspar.genereg.net?ID=MA0065.2&amp;rm=present&amp;collection=CORE">
				<pos i="1" A="0.109685" C="0.369895" G="0.373396" T="0.147025"/>
				<pos i="2" A="0.117716" C="0.193473" G="0.148019" T="0.540793"/>
				<pos i="3" A="0.453488" C="0.026744" G="0.427907" T="0.09186"/>
				<pos i="4" A="0.116144" C="0.003484" G="0.779326" T="0.101045"/>
				<pos i="5" A="0.161253" C="0.017401" G="0.781903" T="0.039443"/>
				<pos i="6" A="0.168213" C="0.149652" G="0.458237" T="0.223898"/>
				<pos i="7" A="0.082271" C="0.633835" G="0.207416" T="0.076477"/>
				<pos i="8" A="0.949015" C="0.024334" G="0.017381" T="0.00927"/>
				<pos i="9" A="0.604867" C="0.05562" G="0.312862" T="0.026651"/>
				<pos i="10" A="0.825231" C="0.005787" G="0.158565" T="0.010417"/>
				<pos i="11" A="0.095017" C="0.002317" G="0.88876" T="0.013905"/>
				<pos i="12" A="0.047509" C="0.010429" G="0.803013" T="0.13905"/>
				<pos i="13" A="0.025492" C="0.114716" G="0.304751" T="0.555041"/>
				<pos i="14" A="0.062645" C="0.643852" G="0.167053" T="0.12645"/>
				<pos i="15" A="0.784223" C="0.067285" G="0.054524" T="0.093968"/>
			</motif>
			<motif id="t_2_MA0066.1" name="MA0066.1" alt="PPARG" length="20" nsites="28" evalue="0.0e+000" url="http://jaspar.genereg.net?ID=MA0066.1&amp;rm=present&amp;collection=CORE">
				<pos i="1" A="0.107143" C="0.285714" G="0.5" T="0.107143"/>
				<pos i="2" A="0.107143" C="0" G="0" T="0.892857"/>
				<pos i="3" A="0.678571" C="0" G="0.321429" T="0"/>
				<pos i="4" A="0" C="0.035714" G="0.964286" T="0"/>